name: 10KHomes
favicon: null
layout_spectrum: 0.6534601473249495
typography_spectrum: 0.9619288393296301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4903167895972729
  lightness: 0.5660043975804001
  saturation: 0.011444545816630125
  rhythmicContrast: 0.49269674555398524
purpose: []
